// <auto-generated />
using System;
using Hodrac_Backend_MVP2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Hodrac_Backend_MVP2.Migrations
{
    [DbContext(typeof(HodracDbContext))]
    [Migration("20260619123624_Creators")]
    partial class Creators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.AggregatedSearchRegistry", b =>
                {
                    b.Property<Guid>("AggregatedSearchRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AdventureDadSearchCount")
                        .HasColumnType("bigint");

                    b.Property<string>("CanonicalSemanticPhrase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FamilyPlannerSearchCount")
                        .HasColumnType("bigint");

                    b.Property<string>("KnownVariantsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("LastSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MasterSearchPhrase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SemanticClusterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Vector>("SemanticEmbedding")
                        .HasColumnType("vector(384)");

                    b.Property<long>("TotalGlobalSearchCount")
                        .HasColumnType("bigint");

                    b.Property<long>("YoungCoupleSearchCount")
                        .HasColumnType("bigint");

                    b.HasKey("AggregatedSearchRegistryId");

                    b.HasIndex("MasterSearchPhrase");

                    b.HasIndex("SemanticClusterId");

                    b.HasIndex("SemanticEmbedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SemanticEmbedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SemanticEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("AggregatedSearchRegistry");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCompletedOnboarding")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayName");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryFlagEmoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DrivingSide")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("EstimatedDailyTaxRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("GlobalHeroImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PowerPlugType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VisaRequirementsSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.CountryLanguage", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("CountryId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CountryLanguages");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Creator", b =>
                {
                    b.Property<Guid>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CreatorId");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("IsVerified");

                    b.HasIndex("PlatformName", "Handle")
                        .IsUnique();

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("ExchangeRateToBase")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("LastExchangeRateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessibilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AdventurePaceScore")
                        .HasColumnType("integer");

                    b.Property<int>("AestheticTrendScore")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageCostPerDay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CleanNormalizedSearchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CommonAlternateSpellingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DoubleMetaphonePrimary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DoubleMetaphoneSecondary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FamilyFriendlyScore")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("LuxuryRating")
                        .HasColumnType("integer");

                    b.Property<string>("MetaphoneCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PsychographicVibeTagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("integer");

                    b.Property<long>("SearchHitCount")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DestinationId");

                    b.HasIndex("AverageCostPerDay");

                    b.HasIndex("CleanNormalizedSearchName");

                    b.HasIndex("CountryId");

                    b.HasIndex("DoubleMetaphonePrimary");

                    b.HasIndex("MetaphoneCode");

                    b.HasIndex("SearchHitCount");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("DestinationId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.HasKey("DestinationId", "CityId");

                    b.HasIndex("CityId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.HasKey("DestinationId", "CurrencyId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationImage", b =>
                {
                    b.Property<Guid>("DestinationImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("ShotContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DestinationImageId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationImages");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("DestinationId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("DestinationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.FeaturedWishlistPool", b =>
                {
                    b.Property<Guid>("FeaturedWishlistPoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentImpressionsToday")
                        .HasColumnType("integer");

                    b.Property<int>("DailyImpressionLimit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastRotationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PoolType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("RandomSelectionWeight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("FeaturedWishlistPoolId");

                    b.HasIndex("WishlistId");

                    b.ToTable("FeaturedWishlistPool");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ItineraryDay", b =>
                {
                    b.Property<Guid>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AfternoonCityId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DayTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EveningCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MorningCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransitFromPreviousDayRouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("AfternoonCityId");

                    b.HasIndex("EveningCityId");

                    b.HasIndex("MorningCityId");

                    b.HasIndex("TransitFromPreviousDayRouteId");

                    b.HasIndex("WishlistId", "DayNumber");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ItineraryItem", b =>
                {
                    b.Property<Guid>("ItineraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IndividualCostModifier")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsOptionalActivity")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelectedByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemOrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("SocialProofBadge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ItineraryItemId");

                    b.HasIndex("ItineraryDayId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HelpfulSurvivalPhrasesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresCertifiedLocalGuide")
                        .HasColumnType("boolean");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.SavedDestination", b =>
                {
                    b.Property<Guid>("SavedDestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SavedDestinationId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId", "DestinationId")
                        .IsUnique();

                    b.ToTable("SavedDestinations");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.SavedWishlist", b =>
                {
                    b.Property<Guid>("SavedWishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("SavedWishlistId");

                    b.HasIndex("WishlistId");

                    b.HasIndex("UserId", "WishlistId")
                        .IsUnique();

                    b.ToTable("SavedWishlists");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TargetPersonaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.TransitRoute", b =>
                {
                    b.Property<Guid>("TransitRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingReferenceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarbonFootprintKg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedCostPerPerson")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecommendedTimeBufferMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SubSegmentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TransitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TransitRouteId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("TransitRoutes");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.UserRefreshToken", b =>
                {
                    b.Property<Guid>("UserRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceHint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserRefreshTokenId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccommodationInclusions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActivityInclusions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BasePricePerPerson")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("CalculatedTotalCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultTravelersCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("DepositAmountRequired")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset?>("FeaturedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ForkedFromId")
                        .HasColumnType("uuid");

                    b.Property<string>("GlobalInclusionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastInteractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeopleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryPersonaTarget")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PsychologicalVibeTagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawContentKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortStory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<long>("TotalGlobalSaveCount")
                        .HasColumnType("bigint");

                    b.Property<string>("TransitInclusions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WishlistDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WishlistHeroImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WishlistId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ForkedFromId");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsTemplate");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TotalGlobalSaveCount");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistCollaborator", b =>
                {
                    b.Property<Guid>("WishlistCollaboratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SharedUserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistCollaboratorId");

                    b.HasIndex("WishlistId", "UserId")
                        .IsUnique();

                    b.ToTable("WishlistCollaborators");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistCreatorAttribution", b =>
                {
                    b.Property<Guid>("WishlistCreatorAttributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributionNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalContentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionEvidenceUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PermissionGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistCreatorAttributionId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PermissionGrantedAt");

                    b.HasIndex("WishlistId", "CreatorId")
                        .IsUnique();

                    b.ToTable("WishlistCreatorAttributions");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistDestination", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistPricingSnapshot", b =>
                {
                    b.Property<Guid>("WishlistPricingSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePricePerPerson")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DepositAmountRequired")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OptionalActivitiesTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SeasonalSurchargePercent")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("TravelersCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistPricingSnapshotId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistPricingSnapshots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.City", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.CountryLanguage", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Country", "Country")
                        .WithMany("CountryLanguages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Language", "Language")
                        .WithMany("CountryLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationImage", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("Images")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.FeaturedWishlistPool", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("FeaturedPoolEntries")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ItineraryDay", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.City", "AfternoonCity")
                        .WithMany()
                        .HasForeignKey("AfternoonCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hodrac_Backend_MVP2.Models.City", "EveningCity")
                        .WithMany()
                        .HasForeignKey("EveningCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hodrac_Backend_MVP2.Models.City", "MorningCity")
                        .WithMany()
                        .HasForeignKey("MorningCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hodrac_Backend_MVP2.Models.TransitRoute", "TransitFromPreviousDayRoute")
                        .WithMany()
                        .HasForeignKey("TransitFromPreviousDayRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AfternoonCity");

                    b.Navigation("EveningCity");

                    b.Navigation("MorningCity");

                    b.Navigation("TransitFromPreviousDayRoute");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ItineraryItem", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.SavedDestination", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.SavedWishlist", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.TransitRoute", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.City", "DestinationCity")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.City", "OriginCity")
                        .WithMany("OriginRoutes")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.UserRefreshToken", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Wishlist", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "ForkedFrom")
                        .WithMany()
                        .HasForeignKey("ForkedFromId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ForkedFrom");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistCollaborator", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("Collaborators")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistCreatorAttribution", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Creator", "Creator")
                        .WithMany("WishlistAttributions")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("CreatorAttributions")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistDestination", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Destination", "Destination")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.WishlistPricingSnapshot", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.Wishlist", "Wishlist")
                        .WithMany("PricingSnapshots")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_Backend_MVP2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Hodrac_Backend_MVP2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.City", b =>
                {
                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationRoutes");

                    b.Navigation("OriginRoutes");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CountryLanguages");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Creator", b =>
                {
                    b.Navigation("WishlistAttributions");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");

                    b.Navigation("Images");

                    b.Navigation("SavedByUsers");

                    b.Navigation("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Language", b =>
                {
                    b.Navigation("CountryLanguages");

                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_Backend_MVP2.Models.Wishlist", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("CreatorAttributions");

                    b.Navigation("FeaturedPoolEntries");

                    b.Navigation("ItineraryDays");

                    b.Navigation("PricingSnapshots");

                    b.Navigation("SavedByUsers");

                    b.Navigation("WishlistDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
